FROM nvidia/cuda:13.1.0-runtime-ubi9

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# HF cache
ENV HF_HOME=/hf_cache
ENV TRANSFORMERS_CACHE=/hf_cache
ENV DIFFUSERS_CACHE=/hf_cache

RUN dnf install -y python3 python3-pip && \
    dnf clean all

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY app /app

WORKDIR /app/app

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]